### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by qufenjt** [DeepImportance/deepimportance_code_release#2]
hello, when i run the source code, an error happend:   "IndexError: list index out of range", and this error is from the 'idc.py'---the function: 'determine_quantized_cover(lout, quantized):'---'closest_q = min(quantized[idx], key=lambda x: abs(x-l))',so maybe the 'idx' is not correct

**Comment by hasanferit** [comment]
Most probably this happens when the relevant neuron number is higher than quantization vector size. The root cause for this might be that you are loading relevant neurons from the file system that can belong to some other model or layer etc... You could try to delete all files produced by DeepImportance and try again.

**Comment by gerasimou** [comment]
Hi @qufenjt, @hasanferit is right, this should be the problem.
The code has been updated, so please take a look at it and let us know if you have any further questions.

**Comment by qufenjt** [comment]
thank you for your reply, and the question has been solved
